Terraform alinka.io domain
CodeForPoznan/Infrastructure pull request #47
Opened 2020-03-04 17:14 UTC by arturtamborski

closes #17 
I've removed the old alinka's bucket, moved stuff to new one in `-public`. Stuff seems to work fine, you can check it out on https://alinka.io

2020-03-04 19:44 UTC, arturtamborski commented
By the way, all of the domains listed in original issue and the resources themselves (the ones i could find) are already imported to tfstate. This code _was_ applied already, by me.

2020-03-05 15:42 UTC, magul requested changes
no need for SES entity validation

2020-03-05 15:42 UTC, magul commented on alinka_website.tf
> +module alinka_website_mailing_identity {
We don't send emails, so that can be removed.

2020-03-05 15:48 UTC, magul approved these changes

2020-03-05 15:48 UTC, merged