[59] Implement dev.cfp_v3 lambdas and DB
CodeForPoznan/Infrastructure pull request #61
Opened 2020-05-19 20:14 UTC by arturtamborski

This was _not_ applied yet, I only provide it as a starting point.

2020-05-27 20:48 UTC, arturtamborski commented
I think its ready to be applied, waiting for review.

2020-07-01 21:06 UTC, magul requested changes
Minor issues, rest looks fine.

2020-07-01 21:06 UTC, magul commented on dev_codeforpoznan_pl_v3.tf
> +resource "aws_iam_user" "dev_codeforpoznan_pl_v3" {
use `./user` module

2020-07-01 21:06 UTC, magul commented on dev_codeforpoznan_pl_v3.tf
> +  name            = "dev_codeforpoznan_pl_v3"
that should end with `_migration` (to have s3 object separate for migration and for API)

2020-07-01 21:06 UTC, magul commented on dev_codeforpoznan_pl_v3.tf
> +  name                = "dev_codeforpoznan_pl_v3"
ditto

2020-07-01 21:16 UTC, arturtamborski commented
updated!

2020-07-01 21:31 UTC, magul submitted a review, later dismissed
this file should be merged with https://github.com/CodeForPoznan/Infrastructure/blob/d655c0a323f76e9c523bd81cf3515f703d76f0d9/codeforpoznan_pl_v3.tf

2020-07-07 19:59 UTC, arturtamborski commented
Update: this PR is now final and ready to be reviewed again! I also applied the change listed here, so all resources listed in diff are either moved over from `codeforpoznan_v3.tf` or created.

Please mind that there is a breaking change (provider specifier in ssl module) which can't work without https://github.com/CodeForPoznan/Infrastructure/pull/72), so that linked PR should be merged first and then this can go cleanly.

2020-07-08 06:55 UTC, Maciek246 approved these changes

2020-07-08 18:03 UTC, merged